In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

from sklearn.preprocessing import LabelEncoder,OneHotEncoder

#Prepocessing

In [8]:
df=pd.read_csv("data.csv") 
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [9]:
df["Salary"].values

array([72000., 48000., 54000., 61000.,    nan, 58000., 52000., 79000.,
       83000., 67000.])

In [13]:
# all features to do preprocessing
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(df.iloc[:,1:3])
df.iloc[:,1:3]=imputer.transform(df.iloc[:,1:3])
df.head()  # transform runs after fit

   Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes

In [22]:

label_encoder=LabelEncoder()
temp=df.copy()
temp.iloc[:,3]=label_encoder.fit_transform(df.iloc[:,3])
temp.head()

   Country   Age        Salary Purchased
0   France  44.0  72000.000000         0
1    Spain  27.0  48000.000000         1
2  Germany  30.0  54000.000000         0
3    Spain  38.0  61000.000000         0
4  Germany  40.0  63777.777778         1

In [21]:

onehort=OneHotEncoder()

In [23]:
# if we convert data into numaric  we can do
# linear reggression  else only logistic regrression work

In [29]:
pd.get_dummies(df.iloc[:,:-1])  # puchna h

         Age        Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.000000            True            False          False
1  27.000000  48000.000000           False            False           True
2  30.000000  54000.000000           False             True          False
3  38.000000  61000.000000           False            False           True
4  40.000000  63777.777778           False             True          False
5  35.000000  58000.000000            True            False          False
6  38.777778  52000.000000           False            False           True
7  48.000000  79000.000000            True            False          False
8  50.000000  83000.000000           False             True          False
9  37.000000  67000.000000            True            False          False